# Generated by Django 5.2.7 on 2025-10-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterequest',
            name='original_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='sample_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
