# Generated by Django 5.2.7 on 2025-10-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_websiterequest_original_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiterequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Website Request', 'verbose_name_plural': 'Website Requests'},
        ),
        migrations.AlterField(
            model_name='websiterequest',
            name='features',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
