# Generated by Django 5.2.7 on 2025-10-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_websiterequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiterequest',
            name='template_file',
            field=models.ImageField(upload_to='templates/'),
        ),
    ]
