# Generated by Django 5.2.7 on 2025-10-18 13:30

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_websiterequest_template_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiterequest',
            name='template_file',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='templates/'),
        ),
    ]
