# Generated by Django 5.2.7 on 2025-10-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='read',
        ),
    ]
