# Generated by Django 5.2.2 on 2025-10-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(default='Free', max_length=100),
        ),
    ]
